### ISSUE TITLE
icicle: compilation error in boost

### ISSUE THREAD

**Issue by mwarusz** [igfuw/libcloudphxx#153]
In file included from /home2/marusz/.local/include/boost/spirit/home/support/common_terminals.hpp:15:0,
                 from /home2/marusz/.local/include/boost/spirit/home/qi/auto/auto.hpp:13,
                 from /home2/marusz/.local/include/boost/spirit/home/qi/auto.hpp:15,
                 from /home2/marusz/.local/include/boost/spirit/home/qi.hpp:15,
                 from /home2/marusz/.local/include/boost/spirit/include/qi.hpp:16,
                 from /home2/marusz/libcloudphxx/tests/paper_GMD_2015/src/opts_lgrngn.hpp:14,
                 from /home2/marusz/libcloudphxx/tests/paper_GMD_2015/src/icicle.cpp:18:
/home2/marusz/.local/include/boost/spirit/home/support/common_terminals.hpp:102:11: error: expected identifier before 'long'
         ( long_long, long_long_type )

encountered when building icicle using local installation of boost. Tested using boost v1.57 and 1.58 build with gcc 4.8.5.

**Comment by slayoo** [comment]
Closing as outdated
